"use client"
import { createContext, useEffect, useState } from 'react'
import styles from './page.module.css'
import axios from 'axios';
import { usePathname, useRouter } from 'next/navigation';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const AuthContext = createContext();

export default function RootLayout({ children }) {
  const [authToken, setAuthToken] = useState("");
  const router = useRouter();
  const pathname = usePathname();
  
  const fetchAuth = async () => {
    if (pathname == "/login") return;
    const res = await axios.get("http://localhost:8080/user/", {
       headers: {Authorization: `Bearer ${authToken}`}
    })
    .catch((e) => {
      router.push("/login");
    })
  }

  useEffect(() => {
    fetchAuth();
  });

  return (
    <html lang="en">
      <body>
        <AuthContext.Provider value={{authToken, setAuthToken}}>
          <main className={styles.main}>
            {children}
          </main>
        </AuthContext.Provider>
      </body>
    </html>
  )
}
